spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/next_db
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db.migration
    enabled: true
    validate-on-migrate: true

